"use strict";
const $ = id => document.getElementById(id);
const candidate = JSON.stringify({name:"Jane Doe",email:"jane@example.com",skills:["Python"],years_experience:4});
const ticket = JSON.stringify({category:"technical",priority:"high",summary:"Cannot sign in",requires_human:true,sentiment:"negative"});
const product = JSON.stringify({name:"Keyboard",price:49.99,currency:"USD",in_stock:true});
const cases = {
  invalid_email:{schema:"candidate",prompt:"Extract Jane Doe, jane@example.com, Python, four years experience.",outputs:[JSON.stringify({name:"Jane Doe",email:"invalid",skills:["Python"],years_experience:4}),candidate]},
  malformed_json:{schema:"candidate",prompt:"Extract Jane Doe, jane@example.com, Python, four years experience.",outputs:["not-json",candidate]},
  invalid_enum:{schema:"support_ticket",prompt:"Classify the sign-in issue.",outputs:[JSON.stringify({category:"unknown",priority:"high",summary:"Cannot sign in",requires_human:true,sentiment:"negative"}),ticket]},
  invalid_price:{schema:"product",prompt:"Extract a keyboard priced at $49.99 USD.",outputs:[JSON.stringify({name:"Keyboard",price:-1,currency:"USD",in_stock:true}),product]},
  retry_exhaustion:{schema:"candidate",prompt:"Extract candidate details.",outputs:["bad","still bad","also bad"]},
  valid_candidate:{schema:"candidate",prompt:"Extract Jane Doe, jane@example.com, Python, four years experience.",outputs:[candidate,candidate]}
};
function loadCase(){const fixture=cases[$("scenario").value];$("schema").value=fixture.schema;$("prompt").value=fixture.prompt;["output1","output2","output3"].forEach((id,i)=>$(id).value=fixture.outputs[i]||"");$("third-wrap").hidden=fixture.outputs.length<3;$("count").value=`${fixture.outputs.length} loaded`;$("retries").value=fixture.outputs.length===3?2:fixture.outputs.length-1;}
function issue(loc,type,msg){return {type,loc:[loc],msg};}
function validate(data,schema){const errors=[];const str=(key,min,max)=>{if(typeof data[key]!=="string")errors.push(issue(key,"string_type","Input should be a valid string"));else if(data[key].length<min||data[key].length>max)errors.push(issue(key,"string_length",`Length must be between ${min} and ${max}`));};const choice=(key,allowed)=>{if(!allowed.includes(data[key]))errors.push(issue(key,"literal_error",`Input should be ${allowed.join(", ")}`));};const number=(key,min,strict)=>{const n=typeof data[key]==="number"?data[key]:typeof data[key]==="string"&&data[key].trim()!==""?Number(data[key]):NaN;if(!Number.isFinite(n))errors.push(issue(key,"float_parsing","Input should be a valid number"));else if(strict?n<=min:n<min)errors.push(issue(key,strict?"greater_than":"greater_than_equal",`Input should be ${strict?"greater than":"greater than or equal to"} ${min}`));else data[key]=n;};
  if(schema==="candidate"){str("name",1,120);if(typeof data.email!=="string"||!(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email)))errors.push(issue("email","value_error","Value is not a valid email address"));if(!Array.isArray(data.skills))errors.push(issue("skills","list_type","Input should be a valid list"));else if(data.skills.length<1)errors.push(issue("skills","too_short","List must have at least 1 item"));number("years_experience",0,false);if(typeof data.years_experience==="number"&&data.years_experience>60)errors.push(issue("years_experience","less_than_equal","Input should be less than or equal to 60"));}
  if(schema==="support_ticket"){choice("category",["billing","technical","account","feature_request","other"]);choice("priority",["low","medium","high","critical"]);str("summary",5,300);if(typeof data.requires_human!=="boolean")errors.push(issue("requires_human","bool_type","Input should be a valid boolean"));choice("sentiment",["negative","neutral","positive"]);}
  if(schema==="product"){str("name",1,160);number("price",0,true);if(typeof data.currency!=="string"||!(/^[A-Z]{3}$/.test(data.currency)))errors.push(issue("currency","string_pattern_mismatch","String should match pattern ^[A-Z]{3}$"));if(typeof data.in_stock!=="boolean")errors.push(issue("in_stock","bool_type","Input should be a valid boolean"));if(data.product_url!=null){try{new URL(data.product_url)}catch{errors.push(issue("product_url","url_parsing","Input should be a valid URL"));}}}
  return errors;
}
function run(){const max=Number($("retries").value);if(!Number.isInteger(max)||max<0||max>10){$("retries").reportValidity();return;}if(!$("prompt").value.trim()){alert("Enter a request prompt.");return;}const schema=$("schema").value;const raw=[$("output1").value,$("output2").value,$("output3").value];const failures=[],trace=[];let data=null,attempts=0,success=false;for(let i=0;i<=max;i++){if(!raw[i]){trace.push({ok:false,title:`Attempt ${i+1} · no simulated response`,message:"Add another provider response to continue. The Python API returns a provider error if a model response is unavailable."});break;}attempts++;let parsed,details=[],type="";try{parsed=JSON.parse(raw[i]);if(parsed===null||Array.isArray(parsed)||typeof parsed!=="object"){type="json_parse_error";details=[{message:"Expected a JSON object at the top level"}];}else{details=validate(parsed,schema);if(details.length)type="pydantic_validation_error";}}catch{type="json_parse_error";details=[{message:"Could not parse JSON"}];}if(!type){data=parsed;if(schema==="product"&&!("product_url" in data))data.product_url=null;success=true;trace.push({ok:true,title:`Attempt ${attempts} · valid`,message:"JSON parsed and schema validation passed."});break;}failures.push({attempt:attempts,error_type:type,details});trace.push({ok:false,title:`Attempt ${attempts} · ${type.replaceAll("_"," ")}`,message:details.map(d=>d.loc?`${d.loc.join(".")}: ${d.msg}`:d.message).join(" · ")});}
  const response={success,schema_name:schema,attempts,validation_failures:failures,data,raw_output:null};$("empty").hidden=true;$("result").hidden=false;$("result").textContent=JSON.stringify(response,null,2);$("status").textContent=success?"Validated":trace.at(-1)?.title.includes("no simulated response")?"Provider unavailable":"Exhausted";$("status").classList.toggle("failure",!success);const list=$("timeline");list.replaceChildren();for(const item of trace){const li=document.createElement("li"),strong=document.createElement("strong"),description=document.createElement("span");li.className=item.ok?"":"bad";strong.textContent=item.title;description.textContent=item.message;li.append(strong,description);list.append(li);}if(!success&&attempts===max+1&&raw[attempts-1]){const li=document.createElement("li");li.textContent="Retry budget exhausted. The agent returns success=false and data=null.";list.append(li);}}
$("scenario").addEventListener("change",loadCase);$("run").addEventListener("click",run);loadCase();
